### ISSUE TITLE
Multiple audio tracks

### ISSUE THREAD

**Issue by test2a** [beeldengeluid/extending-peertube#14]
Hi..
I just found your project while lurking on the main peertube and I have a suggestion to make

https://github.com/Chocobozzz/PeerTube/issues/939

This issue suggests an option to allow multiple audio languages in a video.

I don't know if your project would be willing to support this accessibility feature but this one and another one I would be making a separate issue here, would be super beneficial to billions of people who do not speak English or mandarin but want to consume content. Subtitles only go so much, files like mkv containers have held multiple languages movies for so long and that is one of the easiest way to consume foreign content while hearing in language you understand.

If this project cannot support this issue for any reason, then we will wait for upstream to pick it eventually

**Comment by frankstrater** [comment]
As this is out of scope of our project and already has a temporary workaround by uploading the same video with different audio tracks (and cross-reference them in the description), I'm closing this for now.
