### ISSUE TITLE
Multiple titles/descriptions 

### ISSUE THREAD

**Issue by test2a** [beeldengeluid/extending-peertube#15]
https://github.com/Chocobozzz/PeerTube/issues/2992

I opened this issue upstream because I feel like for having cross language compatibility, its important to have all elements of content accessible so that people can actually decide or understand in the first place.

My example. I cannot read or understand German. Fine. There is so much content in German, but unless the title of a particular content is in english, I would just go past that. Subtitles only come in work if I know what I am looking at. This ties with my last issue request where if possible, we could upload multiple languages of a video for example.

In my example, suppose I am surfing a German instance. Right now I would just quit because I don't understand anything. If we had these two features, the uploader had written the video title and description in German and English. That way, if my instance language is set to English, I would just see the English version of title and description. Instantly I would understand what the whole thing is about. Then, if I select a particular video, I would have English subtitles or if that is an issue, I could have English dubbing audio.

This would be a huge step in accessibility across languages

**Comment by frankstrater** [comment]
There is no need to re-post your issue on this repo, as this is mainly a PeerTube project with limited scope, time and resources with a focus on improving (extending) the utilization of existing feautures. It's best to discuss issues on the main PeerTube repo.

One of the things we are looking into though is the automatic transcription of subtitles (primarily in the same language as the video) to improve it's usage and make the content more accessible to the hearing-impaired, as most video creators on PeerTube don't add subtitles at all.
