### ISSUE TITLE
Use CC Platform Toolkit

### ISSUE THREAD

**Issue by frankstrater** [beeldengeluid/extending-peertube#19]
Use all the steps in the CC Platform Toolkit to guide (and describe) the use of the new CC PeerTube plugin.

https://creativecommons.org/platform/toolkit/ 

It's pretty clear what this is.

> CC PLATFORM TOOLKIT
> INTEGRATING CC TO YOUR PLATFORM

> It’s a guide to implementing CC licenses to uploaded materials. These are best practices, not requirements.

This is what this project is about and the choice of platform is PeerTube.

TODO
- [X] design license display on PeerTube watch view
- [x] settle on final list of licences and their names
- [x] display chosen license name on Watch page
- [x] display chosen license icon on Watch page
- [x] include machine readable license metadata on Watch page

**Comment by frankstrater** [comment]
> WHO
> 
> For platforms who want to offer CC licenses to user uploaded content
> If you’re looking to apply a CC license to your own materials click here.

https://wiki.creativecommons.org/wiki/Marking

**Comment by frankstrater** [comment]
> Give your user context, explain how the CC licenses work, and how your platform’s values align with the CC vision. Click here for resources you can use.

> HOW TO HELP YOUR COMMUNITY GET ON BOARD

> Be transparent
> Explain the basics of CC, why your platform decided to add CC, and how it aligns with your platform’s values. Link https://creativecommons.org for users who want to learn more. Example: YouTube’s page on CC.
> 
> 
> Provide information
> Build a FAQ on how CC licenses work on your platform. You can adapt CC’s FAQ for your purposes. Example: Vimeo’s page on CC.
> 
> 
> Have clear guidelines
> Implement community guidelines around attribution and other sharing practices. Example: Flickr’s attribution and general community guidelines.
> 
> 
> Show the content
> Have a dedicated area for CC works to be found. Build a CC portal for content discovery. Example: Flickr’s CC portal; and Vimeo’s CC portal.

Examples:

https://support.google.com/youtube/answer/2797468?hl=en
https://help.vimeo.com/hc/en-us/articles/224969988-What-is-Creative-Commons-
https://www.flickr.com/services/developer/attributions/

CC search -> included in Sepia Search? https://sepiasearch.org/

**Comment by frankstrater** [comment]
> TYPES OF CONTENT
> 
> ...
> 
> Ensure your user understands the basics of how the licenses work - especially since they’re irrevocable. Decide which of the six license types and two public domain tools you want to enable users to apply. Signal which license applies to which content.
> 
> In nearly all cases, this content remains owned by the user, and the platform gets the rights to host it via the CC license that is applied or via a separate license in the terms of service. 

License chooser link already merged upstream. Suggest example text for terms of service. Create a Github page/website in the plugin repository to accompany this with using the CC plugin. Usage guide in Markdown, but also PDF?

**Comment by frankstrater** [comment]
> CC AND YOUR TERMS OF SERVICE
> 
> Website terms of service are not strictly necessary, but most platforms have them. For those that do, we recommend including the following elements if the platform enables CC licensing for user-generated content.

Make separate issue for testing example CC models terms of service in the admin interface. Administration > Configuration > Instance information: Moderation >> Terms

**Comment by frankstrater** [comment]
> UPDATING TO LATER VERSIONS

Make clear that it's CC version 4 (international). Add to terms of service that earlier CC licenses are not supported?

**Comment by frankstrater** [comment]
> ADDING CC LICENSES

During the upload process

- [x] Let the user license individual work
- [x] Let the user batch license multiple works
- [x] Let the user choose a default license

After uploading content

- [x] Allow easy access to editing licenses
- [x] Give information about the licenses
- [x] Help the user understand the licenses

During:

- License Chooser link
- Tested the API (for batch uploading) with plugin installed: http://localhost:3000/api/v1/videos/licences
- Default license not feasible

After:

- Give information about license > Where? Prepend text & link in description? Below video? How does it procreate with ActivityPub?

**Comment by phivk** [comment]
3rd iteration of graphic design of watch view, displaying license icon underneath Video Title and license name in metadata fields
![peertube-plugin-creativecommons-watch-vNext-3](https://user-images.githubusercontent.com/902958/119803735-002f8c80-bee0-11eb-8ac6-e38647177ee9.png)
