### ISSUE TITLE
Write article on experience of installing PeerTube locally

### ISSUE THREAD

**Issue by phivk** [beeldengeluid/extending-peertube#23]
Sharing perspective of how to get PeerTube up and running on Mac, cover some of the pitfall encountered and solutions found.

Links into the writing as part of https://github.com/beeldengeluid/extending-peertube/issues/20 and posts can cross reference each other.

**Comment by phivk** [comment]
@frankstrater I just pushed a draft of this post: https://github.com/beeldengeluid/extending-peertube/commit/af24bf1436aca58c316ac02c152af3383af41270
could you review, adjust where you see fit and publish?

If you give me a sign when it's published, I'll add a link to https://github.com/beeldengeluid/extending-peertube/blob/gh-pages/_posts/2021-06-16-developing-a-peertube-plugin.md

**Comment by frankstrater** [comment]
@phivk it's published
