### ISSUE TITLE
Investigate Redirecting and Remapping

### ISSUE THREAD

**Issue by frankstrater** [beeldengeluid/extending-peertube#25]
When migrating videos from a video platform to a PeerTube instance there's a possible need for redirecting the old links to video pages to the new video pages when the old platform is disbanded. This way you prevent dead links on the web when URLs to video pages were published/indexed outside your platform.

When importing a video to PeerTube it gets assigned a 32 character unique identifier. You can't choose your own (or have an alias yet, like a slug based on the video title). This means you want to 'map' your old id to your new id. For instance:

From:
https://openbeelden.nl/media/1215504

To:
https://peertube.beeldengeluid.nl/videos/watch/6f41a339-574e-4e85-a01a-6b87e41ad086

This can be easily implemented on any webserver with the use of HTTP Redirects, but gets complicated when you want to add a lot (more than 100) of redirects when migrating a large collection of videos.

**Comment by frankstrater** [comment]
Redirecting and Remapping on Apache web server:

https://httpd.apache.org/docs/2.4/rewrite/
https://httpd.apache.org/docs/2.4/rewrite/remapping.html
https://httpd.apache.org/docs/2.4/rewrite/rewritemap.html

**Comment by frankstrater** [comment]
NGINX:

https://nginx.org/en/docs/http/ngx_http_map_module.html
https://nginx.org/en/docs/hash.html
https://wiki.debian.org/Nginx/DirectoryStructure
https://www.tendenci.com/help-files/nginx-redirect-maps/

- What's the map hash size or hash bucket size for 10.000 redirects?
- What's the best location to add the map file, so it can be included in the conf file?

Keep in mind that RHEL nginx package is different from Debian/Ubuntu nginx package for directory structure. These folders are nginx non-standard, don't exist in RHEL and need to be created:

```
/etc/nginx/sites-available/*  Extra virtual host configuration files
/etc/nginx/sites-enabled/* Symlink to sites-available/<file> to enable vhost
/etc/nginx/snippets/*.conf Configuration snippets that can be included in configs
```

**Comment by MartijnBNG** [comment]
Unfortunately, nginx does not give official, definitive answers.

The best answers I can give you are:
- What's the map hash size or hash bucket size for 10.000 redirects?
I'd say start with a max that is the size of a map file in bytes, and a bucket size of 1024.

All references I've found tell you to use trial and error :( This is the best answer I've found:
https://serverfault.com/questions/703327/nginx-optimal-map-hash-max-size-and-map-hash-bucket-size-for-1m-mapz

Bucket size needs to be a power of 2 (64, 128, 1024 etc) and will create a larger cache. Max size is sometimes mentioned as the full size in bytes, but sometimes less, but still a high number (??). Full size in bytes should always work, but may cause it to be slow.

- What's the best location to add the map file, so it can be included in the conf file?
I've found references to both the main nginx folder (/etc/nginx/) and the snippets folder. Even an occasional reference to de conf.d folder (although that's wrong in my view).

I would place it under de main nginx folder, as all nginx's subfolders have specific jobs, which the map does not match.

**Comment by frankstrater** [comment]
I agree. The map file is an include inside a conf file, so it shouldn't be in one of the existing subfolders. On general I wouldn't put anything in the main folder where the default installed files and subfolders belong, so snippets it is... and that's exactly how the file is included, as a snippet that adheres to the conf syntax and needs a semicolon at the end of each line.

**Comment by frankstrater** [comment]
@MartijnBNG I also agree on the hash sizing. There's no easy way to guess what you need as it's size is dependent on the hardware (memory). I think the best way to approach this is to use the nginx conf tester after adding the mapping directive:

```sh
sudo nginx -t
```

As an example on our test server I got this response (without setting it first)

```
nginx: [warn] could not build optimal map_hash, you should increase either map_hash_max_size: 2048 or map_hash_bucket_size: 64; ignoring map_hash_bucket_size
```

**Comment by frankstrater** [comment]
Following the recommendations from the https://serverfault.com/a/893663 answer:

<ul>
<li>The general recommendation would be to keep both values as small as possible.</li>
<li>If nginx complains increase <code>max_size</code> first as long as it complains. If the number exceeds some big number (32769 for instance), increase <code>bucket_size</code> to multiple of default value on your platform as long as it complains. If it does not complain anymore, decrease <code>max_size</code> back as long as it does not complain. Now you have the best setup for your set of keys (each set of keys may need different setup).</li>
<li>Bigger <code>max_size</code> means more memory consumed (once per worker or server, please comment if you know).</li>
<li>Bigger <code>bucket_size</code> means more CPU cycles (for every key lookup) and more transfers from main memory to cache.</li>
<li><code>max_size</code> is not related to number of keys directly, if number of keys doubles, you may need to increase <code>max_size</code> 10 times or even more to avoid collisions. If you cannot avoid them, you have to increase <code>bucket_size</code>.</li>
<li><code>bucket_size</code> is said to be increased to the next power of two, from the source code I would judge it should be enough to make it multiple of default value, this should keep transfers to cache optimal.</li>
<li>Size of <code>bucket_size</code> depends on length of your keys. Should the average key size be 32 bytes (with hash array overhead), increasing <code>bucket_size</code> to 512 bytes would mean, that it can accommodate 16 keys with colliding hash key. This is not something that you want, if collision happens <a href="https://github.com/nginx/nginx/blob/c3aed0a23392a509f64b740064f5f6633e8c89d8/src/core/ngx_hash.c#L33" rel="noreferrer">it searches linearly</a>. You want to have as less collisions as possible.</li>
<li>If you have <code>max_size</code>  <a href="https://github.com/nginx/nginx/blob/c3aed0a23392a509f64b740064f5f6633e8c89d8/src/core/ngx_hash.c#L289" rel="noreferrer">less than 10000</a> and small <code>bucket_size</code>, you can come across long loading time because nginx would try to find optimal hash size in a loop.</li>
<li>If you have <code>max_size</code> bigger than 10000, there will be "only" 1000 loops performed before it would complain.</li>
</ul>

For a map with 7084 lines with old_id and new_id this results in `/etc/nginx/conf.d/redirect.conf`:

```
map_hash_bucket_size 128;
map_hash_max_size 8192;

map $request_uri $old_id {
    ~^/media/([0-9]+) $1;
}

map $old_id $new_id {
    include /etc/nginx/snippets/rewritemap.conf;
}
```
