### ISSUE TITLE
Write article on Dutch subtitling with Kaldi

### ISSUE THREAD

**Issue by phivk** [beeldengeluid/extending-peertube#28]
Can build on [Handleiding subtitles op PeerTube dmv Kaldi](https://docs.google.com/document/d/1K3hurpW1PB5B_Yzic5pAv9N-xMbMlTU7Ceor-JP-REQ/edit?usp=sharing), but needs to be more general than just KaldiNL (incl. different ways to create subtitles)

**Comment by frankstrater** [comment]
I'll open another issue for the part to generate (automatic, semi-automatic, manual) subtitles/captions.
