### ISSUE TITLE
Setup server for testing

### ISSUE THREAD

**Issue by frankstrater** [beeldengeluid/extending-peertube#6]
Setup a PeerTube server based on the latest stable release. This server will mainly be used for testing content uploads through the use of the PeerTube API and testing maintenance/updates.

https://docs.joinpeertube.org/#/contribute-architecture

https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/production.md
https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/dependencies.md

Target environment is a VM based off default RHEL7 installation as provided by Beeld en Geluid.

**Comment by frankstrater** [comment]
## Should I have a big server to run PeerTube?

Not really. For instance, the demonstration server [https://peertube.cpy.re](https://peertube.cpy.re) has 2 vCore and 2GB of RAM and consumes on average:
 * **CPU** -> nginx ~ 20%, peertube ~ 10%,   postgres ~ 1%, redis ~ 3%
 * **RAM** -> nginx ~ 6MB, peertube ~ 120MB, postgres ~ 10MB, redis ~ 5MB

So you would need:
 * **CPU** 1 core if you don't enable transcoding, 2 at least if you enable it (works with 1 but this is really slow)
 * **RAM** 1GB
 * **Storage** Completely depends on how many videos your users will upload

https://github.com/Chocobozzz/PeerTube/blob/develop/FAQ.md#should-i-have-a-big-server-to-run-peertube

**Comment by jblom** [comment]
@frankstrater how is this different from this server? https://github.com/beeldengeluid/x-omgeving/issues/262

**Comment by frankstrater** [comment]
@jblom Could you provide some details (CPU, RAM, Storage) on the server you have set up?

**Comment by frankstrater** [comment]
Email conversation from september 2019 with the admin of https://tube.piweb.be/

Question:

> I noticed that your instance is also hosted at Hetzner and I really
> like the performance of your instance. Could you give me some insight
> on what type of service you chose? I am currently thinking of picking
> something like the admin of peertube.social described described on
> his/her about page: 2 CPU VPS, with 4 GB RAM and 40 GB disk space
> (CX21) + Storage box

Answer:

> My instance a dedicated VM (KVM) hosted on a my own proxmox server
> (hosted by hetzener).
> 
> Currently I have allocated 4 VCPU and 4Gigabyte of ram for this VM.  For
> the hardware behind it's a dedicated hardware with :
> 
> 8 x Intel(R) Xeon(R) CPU E3-1246 v3 @ 3.50GHz (1 Socket)
> and 32GB of ram.
> 
> I think a 2CPU VPS with 4GB of ram is more than enought for your own
> instance. But if you want to build a public instance it won't fit.

**Comment by frankstrater** [comment]
Beeld en Geluid has provided a testing server in our so-called "experimental environment".

- **CPU** 4 cores
- **RAM** 32GB
- **Storage** 50TB (via nfs mount)
- **OS** Red Hat Enterprise Linux 7
