### ISSUE TITLE
Check dependencies versions during installation

### ISSUE THREAD

**Issue by frankstrater** [beeldengeluid/extending-peertube#8]
The PeerTube dependencies guide doesn't check versions after install and this leads to non-descriptive errors post-install if the dependencies versions were wrong.

There have been countless times has there been frustration and an issue posted in the PeerTube community, because for example a wrong NodeJS version was already installed on the target server.

Although it's recommended to always use a 'clean slate' server before installing PeerTube and it's dependencies, the reality (especially for development as opposed to production) that this is not always feasible.

**Comment by jblom** [comment]
So in my case the Postgres version (9.2) was too low, leading to errors.

For the production guide, I think it would help to put op a table stating the required software + supported version(s) just before the link to "dependencies guide", which focuses on fulfilling these dependencies per OS.

This way it is clear right from the start which software components will be addressed in the dependencies guide.

**Comment by frankstrater** [comment]
I agree, that would be a simple smart addition to the dependencies guide, because this "table" already exists in the main Readme file: https://github.com/Chocobozzz/PeerTube/#dependencies

The dependencies guide is also linked from the [contribution guide](https://github.com/Chocobozzz/PeerTube/blob/develop/.github/CONTRIBUTING.md#develop), so in my opinion the list of required software versions should be included in the dependencies guide itself, instead of putting it before a link to this guide.

I will create a new pull request upstream with this addition.

**Comment by jblom** [comment]
@frankstrater sounds good. Within the guide itself (at the top) makes more sense indeed

**Comment by frankstrater** [comment]
https://github.com/Chocobozzz/PeerTube/pull/3288
